### ISSUE TITLE
Add Your Bitstream Library as a Dependency

### ISSUE THREAD

**Issue by Capital-EX** [lcdr/utils#2]
I spent a while confused as to why the tools weren't working. After looking through the source code I saw you used a library called "bitstream". So after installing it, nothing still worked.  After examining your _account_, I found it depended on your *personal* bitstream library and not [the official bitstream library](https://boisgera.github.io/bitstream/). 

Clarification should be given, especially with the Darkflame Server source code release.

**Comment by jgkawell** [comment]
I'm running into this issue as well. ~How did you install his personal library?~

Figured it out, simply run: `pip3 install git+https://github.com/lcdr/bitstream.git`

**Comment by DomePB** [comment]
Even with the pip installation for the bitstream library it doesnt seem to work

**Comment by Capital-EX** [comment]
I just made a fused fork to simplify the process for others:

https://github.com/Capital-EX/dfs-utils

**Comment by lcdr** [comment]
This is already clearly listed in the readme for this repo. Not sure why you wouldn't look there first.

FWIW, I never expected my tools to be listed in the DLU readme, nor for so many people to be trying to use them. The DLU readme is unclear here, but that's an issue with the DLU readme, not with this repo.

**Comment by Capital-EX** [comment]
I apologize, I had realized after the fact the correct library was in the repo. After doing `pip installed`, I had to install tkinter and just assumed another package like it was missing. Again, I apologize for not reading the README. Your toolkit was quite easy to use after fixing my mistake.

**Comment by lcdr** [comment]
Ah, tkinter is included by default in the standard windows python install, that's why I didn't mention it, what were you using?

**Comment by wiviw5** [comment]
> Ah, tkinter is included by default in the standard windows python install, that's why I didn't mention it, what were you using?

This should really be mentioned for linux users. This appears standard on ubuntu type installs.
