### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by DwarfmanDDH** [lcdr/utils#6]
I am not sure what this error is due to my extreme lack of knowledge.
`File "fdb_to_sqlite.py", line 207, in <module>
    convert(args.fdb_path, args.sqlite_path, args.add_link_info)
  File "fdb_to_sqlite.py", line 51, in __init__
    self.sqlite = sqlite3.connect(out_file)
sqlite3.OperationalError: unable to open database file
`

**Comment by lcdr** [comment]
Sounds like the sqlite file cannot be opened for writing. Did you specify an output path yourself? Do you have permissions to write in the output directory?

**Comment by lcdr** [comment]
Closing for lack of response.
